#Hugo configuration
title = "Test Gallery"
baseURL = "https:\/\/www.exampledomainz.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758397"
subfolder = ""
firstpartycookies = true
cookiedomain = "exampledomainz.com"
